### ISSUE TITLE
cannot be ts compiled when use the waitForUserOperationTransaction method of ECDSAProvider 

### ISSUE THREAD

**Issue by brew0722** [zerodevapp/sdk#61]
When using the `ECDSAProvider` created as `ZeroDevEthersProvider`, the `sendUserOperation` works fine, but when I try to call `waitForUserOperationTransaction`, I got a ts compilation error.
When debugging at runtime, the method binds well to instance.
I haven't taken the time to check it out, but it's probably a little kink in the interface declaration.

```typescript
    let zerodevProvider = await ZeroDevEthersProvider.init("ECDSA", {
      projectId: env.projectId, // zeroDev projectId
      owner: convertEthersSignerToAccountSigner(signer),
      usePaymaster: false,
    });

   ....

    const opResult = await aaProvider.sendUserOperation({
      target: contractAddress as Hex,
      data: unsignedTx.data as Hex,
    });
    this.logger.info("sended userOp", {opResult: opResult});
    // Cannot use below method causes ts compilation error
    // error TS2339: Property 'waitForUserOperationTransaction' does not exist on type 'ECDSAProvider'.
    await aaProvider.waitForUserOperationTransaction(opResult.hash as Hex);
```

```
src/main.ts:69:22 - error TS2339: Property 'waitForUserOperationTransaction' does not exist on type 'ECDSAProvider'.

69     await aaProvider.waitForUserOperationTransaction(opResult.hash as Hex);
                        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

    at createTSError (demo-path/node_modules/ts-node/src/index.ts:859:12)
    at reportTSError (demo-path/node_modules/ts-node/src/index.ts:863:19)
    at getOutput (demo-path/node_modules/ts-node/src/index.ts:1077:36)
    at Object.compile (demo-path/node_modules/ts-node/src/index.ts:1433:41)
    at Module.m._compile (demo-path/node_modules/ts-node/src/index.ts:1617:30)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at Object.require.extensions.<computed> [as .ts] (demo-path/node_modules/ts-node/src/index.ts:1621:12)
    at Module.load (node:internal/modules/cjs/loader:1119:32)
    at Function.Module._load (node:internal/modules/cjs/loader:960:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) {
  diagnosticCodes: [ 2339 ]
```

**Comment by KONFeature** [comment]
Hi, do you also have alchemy account kit packages installed? (like `@alchemy/aa-core`)

I think it can come from here, since ZeroDev use a custom version of the alchemy AA sdk (back from the alpha.23 if my memory is correct), and thus maybe it can conflict with new version of the alchemy AA sdk?

**Comment by brew0722** [comment]
@KONFeature yes, I'm using `"@alchemy/aa-core": "^0.1.0-alpha.23"`
as you know, the `sendUserOperation` method returned hash of userOp, but it typed as 'string' type.
but the `waitForUserOperationTransaction` requires the `Hash` type as `Hex string` type.

**Comment by KONFeature** [comment]
Yeah I see, I encountered some other problem also because of that too, that's why I created [this issue](https://github.com/zerodevapp/sdk/issues/55)
Waiting for them to approve it aha
